// 本文件由“国家二字码(1).xlsx”的 Sheet1 维护生成。
// 仅纳入两位英文字母代码；空值、NULL、数字码及非二字码不会进入国家字典。
pub const COUNTRY_ALIASES: &[(&str, &str, &str, &[&str])] = &[
    ("AT", "Austria", "奥地利", &[]),
    ("AU", "Australia", "澳大利亚", &["澳洲"]),
    ("BE", "Belgium", "比利时", &[]),
    ("BR", "Brazil", "巴西", &[]),
    ("CA", "Canada", "加拿大", &[]),
    ("CH", "Switzerland", "瑞士", &[]),
    ("CN", "China", "中国", &[]),
    ("DE", "Germany", "德国", &["Deutschland"]),
    ("DK", "Denmark", "丹麦", &[]),
    (
        "ES",
        "Spain",
        "西班牙",
        &["巴利阿里群岛", "Balearic Islands"],
    ),
    ("FI", "Finland", "芬兰", &[]),
    ("FR", "France", "法国", &[]),
    (
        "GB",
        "United Kingdom",
        "英国",
        &["UK", "Great Britain", "England", "Britain", "英国-万邑通"],
    ),
    ("IE", "Ireland", "爱尔兰", &[]),
    ("IT", "Italy", "意大利", &[]),
    ("JP", "Japan", "日本", &[]),
    ("KR", "South Korea", "韩国", &["Korea"]),
    ("MX", "Mexico", "墨西哥", &[]),
    ("MY", "Malaysia", "马来西亚", &[]),
    ("NL", "Netherlands", "荷兰", &["Holland"]),
    ("NO", "Norway", "挪威", &[]),
    ("NZ", "New Zealand", "新西兰", &[]),
    ("PH", "Philippines", "菲律宾", &[]),
    ("SE", "Sweden", "瑞典", &[]),
    ("SG", "Singapore", "新加坡", &[]),
    ("TH", "Thailand", "泰国", &[]),
    (
        "US",
        "United States",
        "美国",
        &["USA", "United States of America", "America"],
    ),
    ("VN", "Vietnam", "越南", &[]),
    ("AD", "Andorra", "安道尔", &[]),
    ("AE", "United Arab Emirates 1", "阿联酋", &[]),
    ("AF", "Afghanistan", "阿富汗", &[]),
    ("AG", "Antigua", "安提瓜", &[]),
    ("AI", "Anguilla", "安圭拉", &[]),
    ("AL", "Albania", "阿尔巴尼亚", &[]),
    ("AM", "Armenia", "亚美尼亚", &[]),
    ("AN", "Netherlands Antilles", "荷属安的列斯群岛", &[]),
    ("AO", "Angola", "安哥拉", &[]),
    ("AQ", "Antarctica", "南极洲", &[]),
    ("AR", "Argentina", "阿根廷", &[]),
    ("AS", "Amercian Samoa", "美属萨摩亚", &[]),
    ("AW", "Aruba", "阿鲁巴", &[]),
    ("AX", "Aland Islands", "奥兰群岛", &[]),
    ("AZ", "Azerbaijan", "阿塞拜疆", &[]),
    ("BA", "Bosnia and Herzegovina", "波黑", &[]),
    ("BB", "Barbados", "巴巴多斯", &[]),
    ("BD", "Bengal", "孟加拉国", &[]),
    ("BF", "Burkina Faso", "布基纳法索", &[]),
    ("BG", "Bulgaria", "保加利亚", &[]),
    ("BH", "Bahrain", "巴林", &[]),
    ("BI", "Burundi", "布隆迪", &[]),
    ("BJ", "Benin", "贝宁", &[]),
    ("BL", "Saint Barthelemy", "圣巴泰勒米岛", &[]),
    ("BM", "Bermuda", "百慕大", &["百慕大群岛", "Bermuda 1"]),
    ("BN", "Brunei", "文莱", &[]),
    ("BO", "Bolivia", "玻利维亚", &[]),
    ("BQ", "Bonaire", "博奈尔、圣尤斯特歇斯和萨巴", &[]),
    ("BS", "Bahamas", "巴哈马", &[]),
    ("BT", "Bhutan", "不丹", &[]),
    ("BV", "Bouvet Island", "布维岛", &[]),
    ("BW", "Botswana", "博茨瓦纳", &[]),
    ("BY", "Belarus", "白俄罗斯", &[]),
    ("BZ", "Belize", "伯利兹", &[]),
    ("CC", "Cocos Islands (Keeling)", "科科斯群岛", &[]),
    ("CD", "Democratic Republic of the Congo", "刚果(金)", &[]),
    ("CF", "The Central African Republic", "中非", &[]),
    (
        "CI",
        "The Republic of Ivory Coast",
        "象牙海岸",
        &["科特迪瓦", "Cotedivoire"],
    ),
    ("CK", "Cook Islands", "库克群岛", &[]),
    ("CL", "Chile", "智利", &[]),
    ("CM", "Cameroon", "喀麦隆", &[]),
    ("CO", "Colombia", "哥伦比亚", &[]),
    ("CR", "Costarica", "哥斯达黎加", &[]),
    ("CU", "Cuba", "古巴", &[]),
    ("CV", "The Republic of Cape Verde", "佛得角", &[]),
    ("CY", "Cyprus", "塞浦路斯", &[]),
    ("CZ", "Czech Rep.", "捷克", &[]),
    ("DJ", "Djibouti", "吉布提", &[]),
    (
        "DM",
        "The Commonwealth of Dominica",
        "多米尼克",
        &["多米尼加岛", "Dominica"],
    ),
    ("DO", "DOMINICAN REPUBLIC", "多米尼加共和国", &[]),
    ("DZ", "Algeria", "阿尔及利亚", &[]),
    ("EC", "Ecuador", "厄瓜多尔", &[]),
    ("EE", "Estonia", "爱沙尼亚", &[]),
    ("EG", "Egypt", "埃及", &[]),
    ("ET", "Ethiopia", "埃塞俄比亚", &[]),
    ("FJ", "Fiji", "斐济", &[]),
    ("FK", "Islas Malvinas", "福克兰群岛", &[]),
    ("FM", "Micronesia", "密克罗尼西亚", &[]),
    ("FO", "The Faroe Islands", "法罗群岛", &[]),
    ("GA", "Gabon", "加蓬", &[]),
    ("GD", "Grenada", "格林纳达", &[]),
    ("GE", "Georgia", "格鲁吉亚", &[]),
    ("GF", "Guyane Francaise", "法属圭亚那", &[]),
    ("GG", "Guernsey", "根西岛", &["格恩西岛"]),
    ("GH", "Ghana", "加纳", &[]),
    ("GI", "Gibraltar", "直布罗陀", &[]),
    ("GL", "Greenland", "格陵兰岛", &[]),
    ("GM", "Gambian", "冈比亚", &[]),
    ("GN", "Guinea", "几内亚", &[]),
    ("GP", "Guadeloupe", "瓜德罗普", &[]),
    ("GQ", "equatorial guinea", "赤道几内亚", &[]),
    ("GR", "Greece", "希腊", &[]),
    (
        "GS",
        "South Georgia and the South Sandwich Islands",
        "南乔治亚岛和南桑威奇群岛",
        &[],
    ),
    ("GT", "Guatemala", "危地马拉", &[]),
    ("GU", "Guam", "关岛", &[]),
    ("GW", "Guinea-Bissau", "几内亚比绍", &[]),
    ("GY", "Guyana", "圭亚那", &[]),
    ("HK", "Hongkong China", "中国香港", &[]),
    ("HN", "Honduras", "洪都拉斯", &[]),
    ("HR", "Croatia", "克罗地亚", &[]),
    ("HT", "Haiti", "海地", &[]),
    ("HU", "Hungary", "匈牙利", &[]),
    ("IC", "Canary Islands", "加那利群岛", &[]),
    ("ID", "Indonesia", "印度尼西亚", &[]),
    ("IL", "Israel", "以色列", &[]),
    ("IM", "Isle of Man, British Dependency", "马恩岛", &[]),
    ("IN", "India", "印度", &[]),
    (
        "IO",
        "British Indian Ocean Territory",
        "英属印度洋领地",
        &[],
    ),
    ("IQ", "Iraq", "伊拉克", &[]),
    ("IR", "Iran", "伊朗", &[]),
    ("IS", "Iceland", "冰岛", &[]),
    ("JE", "Jersey", "泽西岛", &[]),
    ("JM", "Jamaica", "牙买加", &[]),
    ("JO", "Jordan", "约旦", &[]),
    ("KE", "Kenya", "肯尼亚", &[]),
    ("KG", "Kirghizia", "吉尔吉斯斯坦", &[]),
    ("KH", "Cambodia", "柬埔寨", &[]),
    ("KI", "Kiribati", "基里巴斯", &[]),
    ("KM", "Union of Comoros", "科摩罗", &[]),
    (
        "KN",
        "The Federation of Saint Kitts and Nevis",
        "圣基茨和尼维斯联邦",
        &[],
    ),
    ("KP", "North Korea", "朝鲜", &[]),
    ("KS", "Kosovo", "科索沃", &[]),
    ("KW", "Kuwait", "科威特", &[]),
    ("KY", "Cayman Islands", "开曼群岛", &[]),
    ("KZ", "Kazakhstan", "哈萨克斯坦", &[]),
    ("LA", "Laos", "老挝", &[]),
    ("LB", "Lebanon", "黎巴嫩", &[]),
    ("LC", "Saint Lucia", "圣卢西亚", &[]),
    ("LI", "Liechtenstein", "列支敦士登", &[]),
    ("LK", "Sri Lanka", "斯里兰卡", &[]),
    ("LR", "Liberia", "利比里亚", &[]),
    ("LS", "The Kingdom of Lesotho", "莱索托", &[]),
    ("LT", "Lithuania", "立陶宛", &[]),
    ("LU", "Luxemburg", "卢森堡", &[]),
    ("LV", "Latvia", "拉脱维亚", &[]),
    ("LY", "Libya", "利比亚", &[]),
    ("MA", "Morocco", "摩洛哥", &[]),
    ("MC", "Monaco", "摩纳哥", &[]),
    ("MD", "Moldova", "摩尔多瓦", &[]),
    ("ME", "The Republic of Montenegro", "黑山", &[]),
    ("MF", "Saint Martin", "圣马丁", &[]),
    (
        "MG",
        "Madagascar",
        "马达加斯加",
        &["马德拉群岛", "Madeira Islands"],
    ),
    ("MH", "Marshall Island", "马绍尔群岛", &[]),
    ("MK", "Macedonia", "北马其顿", &[]),
    ("ML", "Mali", "马里", &[]),
    ("MM", "Burma", "缅甸", &[]),
    ("MN", "Mongolia", "蒙古", &[]),
    ("MO", "Macao China", "中国澳门", &[]),
    (
        "MP",
        "Saipan lsland",
        "塞班岛",
        &["马里亚纳群岛", "北马里亚纳群岛"],
    ),
    ("MQ", "Martinique", "马提尼克", &[]),
    ("MR", "Mauritania", "毛里塔尼亚", &[]),
    ("MT", "Malta", "马耳他", &[]),
    ("MU", "Mauritius", "毛里求斯", &[]),
    ("MV", "Maldives", "马尔代夫", &[]),
    ("MW", "Malawi", "马拉维", &[]),
    ("MZ", "Mozambique", "莫桑比克", &[]),
    ("NA", "Namibia", "纳米比亚", &[]),
    ("NC", "New Caledonia", "新加勒多尼亚", &["新喀里多尼亚"]),
    ("NE", "Niger", "尼日尔", &[]),
    ("NF", "Norfolk Island", "诺福克岛", &[]),
    ("NG", "Nigeria", "尼日利亚", &[]),
    ("NI", "Nicaragua", "尼加拉瓜", &[]),
    ("NP", "Nepal", "尼泊尔", &[]),
    ("NR", "The Republic of Nauru", "瑙鲁共和国", &[]),
    ("NU", "Niue", "纽埃", &[]),
    ("OM", "Oman", "阿曼", &[]),
    ("PA", "Panama", "巴拿马", &[]),
    ("PE", "Peru", "秘鲁", &[]),
    (
        "PF",
        "Polynesia",
        "波利尼西亚",
        &["法属波利尼西亚", "FRENCH POLYNESIA"],
    ),
    ("PG", "Papua New Guinea", "巴布亚新几内亚", &[]),
    ("PK", "Pakistan", "巴基斯坦", &[]),
    ("PL", "Poland", "波兰", &[]),
    ("PM", "Saint Pierre and Miquelon", "圣皮埃尔和密克隆", &[]),
    ("PN", "Pitcairn Islands", "皮特凯恩群岛", &[]),
    ("PR", "Porto Rico", "波多黎各", &[]),
    ("PS", "Palestine", "巴勒斯坦", &[]),
    ("PT", "Portugal", "葡萄牙", &["亚速尔群岛", "Azores"]),
    ("PW", "The Republic of Palau", "帕劳", &[]),
    ("PY", "Paraguay", "巴拉圭", &[]),
    ("QA", "Qatar", "卡塔尔", &[]),
    ("RA", "remote area of us", "美国偏远地区", &[]),
    ("RE", "Reunion Island", "留尼汪岛", &[]),
    ("RO", "Romania", "罗马尼亚", &[]),
    ("RS", "Serbia", "塞尔维亚", &[]),
    ("RU", "Russian", "俄罗斯", &[]),
    ("RW", "Rwanda", "卢旺达", &[]),
    ("SA", "Saudi Arabia", "沙特阿拉伯", &[]),
    ("SB", "Solomon Islands", "所罗门群岛", &[]),
    ("SC", "Seychelles", "塞舌尔", &[]),
    ("SD", "Sudan", "苏丹", &[]),
    ("SH", "Saint Helena", "圣赫勒拿", &[]),
    ("SI", "Slovenia", "斯洛文尼亚", &[]),
    (
        "SJ",
        "The Svalbard archipelago",
        "斯瓦尔巴岛和扬马延岛",
        &[],
    ),
    ("SK", "Slovakia", "斯洛伐克", &[]),
    ("SL", "Sierra Leone", "塞拉利昂", &[]),
    ("SM", "San Marino", "圣马力诺", &[]),
    ("SN", "Senegal", "塞内加尔", &[]),
    ("SO", "Somali", "索马里", &[]),
    ("SR", "Suriname", "苏里南", &[]),
    ("SS", "SOUTH SUDAN", "南苏丹共和国", &[]),
    ("SV", "Salvador", "萨尔瓦多", &[]),
    ("SX", "St.Maarten", "荷属圣马丁", &[]),
    ("SY", "Syria", "叙利亚", &[]),
    ("SZ", "Swaziland", "斯威士兰", &[]),
    ("TA", "Tristan da Cunha", "特里斯坦达库尼亚群岛", &[]),
    (
        "TC",
        "The Turks and Caicos Islands",
        "特克斯和凯科斯群岛",
        &[],
    ),
    ("TF", "fashunanbulingdi", "法属南部领地", &[]),
    ("TG", "Togo", "多哥", &[]),
    ("TJ", "Tajikistan", "塔吉克斯坦", &[]),
    ("TL", "Democratic Republic of Timor-Leste", "东帝汶", &[]),
    ("TM", "Turkmenistan", "土库曼斯坦", &[]),
    ("TN", "Tunis", "突尼斯", &[]),
    ("TO", "Tonga", "汤加", &[]),
    ("TR", "Turkey", "土耳其", &[]),
    ("TT", "Trinidad and Tobago", "多巴哥", &["特立尼达和多巴哥"]),
    ("TV", "Tuvalu", "图瓦卢", &[]),
    ("TW", "Taiwan China", "中国台湾", &[]),
    ("TZ", "Tanzania", "坦桑尼亚", &[]),
    ("UA", "Ukraine", "乌克兰", &[]),
    ("UG", "Uganda", "乌干达", &[]),
    (
        "UM",
        "United States Minor Outlying Islands",
        "美国本土外小岛屿",
        &[],
    ),
    ("UY", "Uruguay", "乌拉圭", &[]),
    ("UZ", "Uzbekistan", "乌兹别克斯坦", &[]),
    ("VA", "Vatican", "梵蒂冈", &[]),
    (
        "VC",
        "Saint Vincent and the Grenadines",
        "圣文森特和格林纳丁斯",
        &[],
    ),
    ("VE", "Venezuela", "委内瑞拉", &[]),
    ("VG", "THE BRITISH VRIGIN ISLANDS", "英属维尔京", &[]),
    (
        "VI",
        "The United States Virgin Islands",
        "美属维尔京群岛",
        &[],
    ),
    ("VU", "Vanuatu", "瓦努阿图", &[]),
    ("WF", "Wallis et Futuna", "瓦利斯和富图纳群岛", &[]),
    (
        "WS",
        "Samoa",
        "萨摩亚",
        &["西萨摩亚", "The Independent State of Samoa"],
    ),
    ("YE", "Yemen", "也门", &[]),
    ("YT", "Territorial Collectivity of Mayotte", "马约特", &[]),
    ("ZA", "South Africa", "南非", &[]),
    ("ZM", "Zambia", "赞比亚", &[]),
    ("ZW", "Zimbabwe", "津巴布韦", &[]),
];
