// 本文件由“国家二字码(1).xlsx”的 Sheet1 维护生成，并按当前 ISO/联合国名称校正。
// 主名称使用当前标准名称；历史名称和业务名称保留为别名，保证已有订单仍可识别。
// 仅纳入两位英文字母代码；空值、NULL、数字码及非二字码不会进入国家字典。
pub const COUNTRY_ALIASES: &[(&str, &str, &str, &[&str])] = &[
    ("AT", "Austria", "奥地利", &[]),
    ("AU", "Australia", "澳大利亚", &["澳洲"]),
    ("BE", "Belgium", "比利时", &[]),
    ("BR", "Brazil", "巴西", &[]),
    ("CA", "Canada", "加拿大", &[]),
    ("CH", "Switzerland", "瑞士", &[]),
    ("CN", "China", "中国", &[]),
    ("DE", "Germany", "德国", &["Deutschland"]),
    ("DK", "Denmark", "丹麦", &[]),
    (
        "ES",
        "Spain",
        "西班牙",
        &["巴利阿里群岛", "Balearic Islands"],
    ),
    ("FI", "Finland", "芬兰", &[]),
    ("FR", "France", "法国", &[]),
    (
        "GB",
        "United Kingdom",
        "英国",
        &[
            "UK",
            "Great Britain",
            "England",
            "Britain",
            "英国-万邑通",
            "United Kingdom of Great Britain and Northern Ireland",
            "大不列颠及北爱尔兰联合王国",
        ],
    ),
    ("IE", "Ireland", "爱尔兰", &[]),
    ("IT", "Italy", "意大利", &[]),
    ("JP", "Japan", "日本", &[]),
    (
        "KR",
        "Republic of Korea",
        "大韩民国",
        &["South Korea", "韩国", "Korea"],
    ),
    ("MX", "Mexico", "墨西哥", &[]),
    ("MY", "Malaysia", "马来西亚", &[]),
    (
        "NL",
        "Netherlands",
        "荷兰",
        &["Holland", "Netherlands (Kingdom of the)", "荷兰王国"],
    ),
    ("NO", "Norway", "挪威", &[]),
    ("NZ", "New Zealand", "新西兰", &[]),
    ("PH", "Philippines", "菲律宾", &[]),
    ("SE", "Sweden", "瑞典", &[]),
    ("SG", "Singapore", "新加坡", &[]),
    ("TH", "Thailand", "泰国", &[]),
    (
        "US",
        "United States",
        "美国",
        &["USA", "United States of America", "America", "美利坚合众国"],
    ),
    ("VN", "Vietnam", "越南", &[]),
    ("AD", "Andorra", "安道尔", &[]),
    (
        "AE",
        "United Arab Emirates",
        "阿拉伯联合酋长国",
        &["United Arab Emirates 1", "阿联酋"],
    ),
    ("AF", "Afghanistan", "阿富汗", &[]),
    (
        "AG",
        "Antigua and Barbuda",
        "安提瓜和巴布达",
        &["Antigua", "安提瓜"],
    ),
    ("AI", "Anguilla", "安圭拉", &[]),
    ("AL", "Albania", "阿尔巴尼亚", &[]),
    ("AM", "Armenia", "亚美尼亚", &[]),
    ("AN", "Netherlands Antilles", "荷属安的列斯群岛", &[]),
    ("AO", "Angola", "安哥拉", &[]),
    ("AQ", "Antarctica", "南极洲", &[]),
    ("AR", "Argentina", "阿根廷", &[]),
    ("AS", "American Samoa", "美属萨摩亚", &["Amercian Samoa"]),
    ("AW", "Aruba", "阿鲁巴", &[]),
    ("AX", "Åland Islands", "奥兰群岛", &["Aland Islands"]),
    ("AZ", "Azerbaijan", "阿塞拜疆", &[]),
    (
        "BA",
        "Bosnia and Herzegovina",
        "波斯尼亚和黑塞哥维那",
        &["波黑"],
    ),
    ("BB", "Barbados", "巴巴多斯", &[]),
    ("BD", "Bangladesh", "孟加拉国", &["Bengal"]),
    ("BF", "Burkina Faso", "布基纳法索", &[]),
    ("BG", "Bulgaria", "保加利亚", &[]),
    ("BH", "Bahrain", "巴林", &[]),
    ("BI", "Burundi", "布隆迪", &[]),
    ("BJ", "Benin", "贝宁", &[]),
    (
        "BL",
        "Saint Barthélemy",
        "圣巴泰勒米",
        &["Saint Barthelemy", "圣巴泰勒米岛"],
    ),
    ("BM", "Bermuda", "百慕大", &["百慕大群岛", "Bermuda 1"]),
    (
        "BN",
        "Brunei Darussalam",
        "文莱达鲁萨兰国",
        &["Brunei", "文莱"],
    ),
    (
        "BO",
        "Bolivia (Plurinational State of)",
        "多民族玻利维亚国",
        &["Bolivia", "玻利维亚"],
    ),
    (
        "BQ",
        "Bonaire, Sint Eustatius and Saba",
        "博纳尔，圣俄斯塔休斯和萨巴",
        &["Bonaire", "博奈尔、圣尤斯特歇斯和萨巴"],
    ),
    ("BS", "Bahamas", "巴哈马", &[]),
    ("BT", "Bhutan", "不丹", &[]),
    ("BV", "Bouvet Island", "布维岛", &[]),
    ("BW", "Botswana", "博茨瓦纳", &[]),
    ("BY", "Belarus", "白俄罗斯", &[]),
    ("BZ", "Belize", "伯利兹", &[]),
    (
        "CC",
        "Cocos (Keeling) Islands",
        "科科斯（基林）群岛",
        &["Cocos Islands (Keeling)", "科科斯群岛"],
    ),
    (
        "CD",
        "Democratic Republic of the Congo",
        "刚果民主共和国",
        &["刚果(金)"],
    ),
    (
        "CF",
        "Central African Republic",
        "中非共和国",
        &["The Central African Republic", "中非"],
    ),
    ("CG", "Congo", "刚果", &[]),
    (
        "CI",
        "Côte d’Ivoire",
        "象牙海岸",
        &["The Republic of Ivory Coast", "科特迪瓦", "Cotedivoire"],
    ),
    ("CK", "Cook Islands", "库克群岛", &[]),
    ("CL", "Chile", "智利", &[]),
    ("CM", "Cameroon", "喀麦隆", &[]),
    ("CO", "Colombia", "哥伦比亚", &[]),
    ("CR", "Costa Rica", "哥斯达黎加", &["Costarica"]),
    ("CU", "Cuba", "古巴", &[]),
    (
        "CV",
        "Cabo Verde",
        "佛得角",
        &["The Republic of Cape Verde", "Cape Verde"],
    ),
    ("CY", "Cyprus", "塞浦路斯", &[]),
    ("CW", "Curaçao", "库拉索", &["Curacao"]),
    ("CX", "Christmas Island", "圣诞岛", &[]),
    ("CZ", "Czechia", "捷克", &["Czech Rep.", "Czech Republic"]),
    ("DJ", "Djibouti", "吉布提", &[]),
    (
        "DM",
        "The Commonwealth of Dominica",
        "多米尼克",
        &["多米尼加岛", "Dominica"],
    ),
    ("DO", "Dominican Republic", "多米尼加", &["多米尼加共和国"]),
    ("DZ", "Algeria", "阿尔及利亚", &[]),
    ("EC", "Ecuador", "厄瓜多尔", &[]),
    ("EE", "Estonia", "爱沙尼亚", &[]),
    ("EG", "Egypt", "埃及", &[]),
    ("EH", "Western Sahara", "西撒哈拉", &[]),
    ("ER", "Eritrea", "厄立特里亚", &[]),
    ("ET", "Ethiopia", "埃塞俄比亚", &[]),
    ("FJ", "Fiji", "斐济", &[]),
    (
        "FK",
        "Falkland Islands (Malvinas)",
        "福克兰群岛（马尔维纳斯）",
        &["Islas Malvinas", "福克兰群岛"],
    ),
    (
        "FM",
        "Micronesia (Federated States of)",
        "密克罗尼西亚联邦",
        &["Micronesia", "密克罗尼西亚"],
    ),
    ("FO", "Faroe Islands", "法罗群岛", &["The Faroe Islands"]),
    ("GA", "Gabon", "加蓬", &[]),
    ("GD", "Grenada", "格林纳达", &[]),
    ("GE", "Georgia", "格鲁吉亚", &[]),
    ("GF", "French Guiana", "法属圭亚那", &["Guyane Francaise"]),
    ("GG", "Guernsey", "格恩西", &["根西岛", "格恩西岛"]),
    ("GH", "Ghana", "加纳", &[]),
    ("GI", "Gibraltar", "直布罗陀", &[]),
    ("GL", "Greenland", "格陵兰", &["格陵兰岛"]),
    ("GM", "Gambia", "冈比亚", &["Gambian"]),
    ("GN", "Guinea", "几内亚", &[]),
    ("GP", "Guadeloupe", "瓜德罗普", &[]),
    ("GQ", "equatorial guinea", "赤道几内亚", &[]),
    ("GR", "Greece", "希腊", &[]),
    (
        "GS",
        "South Georgia and the South Sandwich Islands",
        "南乔治亚岛和南桑德韦奇岛",
        &["南乔治亚岛和南桑威奇群岛"],
    ),
    ("GT", "Guatemala", "危地马拉", &[]),
    ("GU", "Guam", "关岛", &[]),
    ("GW", "Guinea-Bissau", "几内亚比绍", &[]),
    ("GY", "Guyana", "圭亚那", &[]),
    (
        "HK",
        "China, Hong Kong Special Administrative Region",
        "中国香港特别行政区",
        &["Hong Kong", "Hongkong China", "中国香港"],
    ),
    ("HN", "Honduras", "洪都拉斯", &[]),
    ("HR", "Croatia", "克罗地亚", &[]),
    ("HT", "Haiti", "海地", &[]),
    ("HU", "Hungary", "匈牙利", &[]),
    (
        "HM",
        "Heard Island and McDonald Islands",
        "赫德岛和麦克唐纳岛",
        &[],
    ),
    ("IC", "Canary Islands", "加那利群岛", &[]),
    ("ID", "Indonesia", "印度尼西亚", &[]),
    ("IL", "Israel", "以色列", &[]),
    (
        "IM",
        "Isle of Man",
        "马恩岛",
        &["Isle of Man, British Dependency"],
    ),
    ("IN", "India", "印度", &[]),
    (
        "IO",
        "British Indian Ocean Territory",
        "英属印度洋领土",
        &["英属印度洋领地"],
    ),
    ("IQ", "Iraq", "伊拉克", &[]),
    (
        "IR",
        "Iran (Islamic Republic of)",
        "伊朗伊斯兰共和国",
        &["Iran", "伊朗"],
    ),
    ("IS", "Iceland", "冰岛", &[]),
    ("JE", "Jersey", "泽西", &["泽西岛"]),
    ("JM", "Jamaica", "牙买加", &[]),
    ("JO", "Jordan", "约旦", &[]),
    ("KE", "Kenya", "肯尼亚", &[]),
    ("KG", "Kyrgyzstan", "吉尔吉斯斯坦", &["Kirghizia"]),
    ("KH", "Cambodia", "柬埔寨", &[]),
    ("KI", "Kiribati", "基里巴斯", &[]),
    ("KM", "Comoros", "科摩罗", &["Union of Comoros"]),
    (
        "KN",
        "Saint Kitts and Nevis",
        "圣基茨和尼维斯",
        &[
            "The Federation of Saint Kitts and Nevis",
            "圣基茨和尼维斯联邦",
        ],
    ),
    (
        "KP",
        "Democratic People's Republic of Korea",
        "朝鲜民主主义人民共和国",
        &["North Korea", "朝鲜"],
    ),
    ("KS", "Kosovo", "科索沃", &[]),
    ("KW", "Kuwait", "科威特", &[]),
    ("KY", "Cayman Islands", "开曼群岛", &[]),
    ("KZ", "Kazakhstan", "哈萨克斯坦", &[]),
    (
        "LA",
        "Lao People's Democratic Republic",
        "老挝人民民主共和国",
        &["Laos", "老挝"],
    ),
    ("LB", "Lebanon", "黎巴嫩", &[]),
    ("LC", "Saint Lucia", "圣卢西亚", &[]),
    ("LI", "Liechtenstein", "列支敦士登", &[]),
    ("LK", "Sri Lanka", "斯里兰卡", &[]),
    ("LR", "Liberia", "利比里亚", &[]),
    ("LS", "Lesotho", "莱索托", &["The Kingdom of Lesotho"]),
    ("LT", "Lithuania", "立陶宛", &[]),
    ("LU", "Luxembourg", "卢森堡", &["Luxemburg"]),
    ("LV", "Latvia", "拉脱维亚", &[]),
    ("LY", "Libya", "利比亚", &[]),
    ("MA", "Morocco", "摩洛哥", &[]),
    ("MC", "Monaco", "摩纳哥", &[]),
    (
        "MD",
        "Republic of Moldova",
        "摩尔多瓦共和国",
        &["Moldova", "摩尔多瓦"],
    ),
    ("ME", "Montenegro", "黑山", &["The Republic of Montenegro"]),
    (
        "MF",
        "Saint Martin (French Part)",
        "圣马丁（法属）",
        &["Saint Martin", "圣马丁"],
    ),
    (
        "MG",
        "Madagascar",
        "马达加斯加",
        &["马德拉群岛", "Madeira Islands"],
    ),
    ("MH", "Marshall Islands", "马绍尔群岛", &["Marshall Island"]),
    ("MK", "North Macedonia", "北马其顿", &["Macedonia"]),
    ("ML", "Mali", "马里", &[]),
    ("MM", "Myanmar", "缅甸", &["Burma"]),
    ("MN", "Mongolia", "蒙古", &[]),
    (
        "MO",
        "China, Macao Special Administrative Region",
        "中国澳门特别行政区",
        &["Macao", "Macao China", "中国澳门", "Macau"],
    ),
    (
        "MP",
        "Northern Mariana Islands",
        "北马里亚纳群岛",
        &["Saipan lsland", "Saipan Island", "塞班岛", "马里亚纳群岛"],
    ),
    ("MQ", "Martinique", "马提尼克", &[]),
    ("MR", "Mauritania", "毛里塔尼亚", &[]),
    ("MS", "Montserrat", "蒙特塞拉特", &[]),
    ("MT", "Malta", "马耳他", &[]),
    ("MU", "Mauritius", "毛里求斯", &[]),
    ("MV", "Maldives", "马尔代夫", &[]),
    ("MW", "Malawi", "马拉维", &[]),
    ("MZ", "Mozambique", "莫桑比克", &[]),
    ("NA", "Namibia", "纳米比亚", &[]),
    ("NC", "New Caledonia", "新加勒多尼亚", &["新喀里多尼亚"]),
    ("NE", "Niger", "尼日尔", &[]),
    ("NF", "Norfolk Island", "诺福克岛", &[]),
    ("NG", "Nigeria", "尼日利亚", &[]),
    ("NI", "Nicaragua", "尼加拉瓜", &[]),
    ("NP", "Nepal", "尼泊尔", &[]),
    (
        "NR",
        "Nauru",
        "瑙鲁",
        &["The Republic of Nauru", "瑙鲁共和国"],
    ),
    ("NU", "Niue", "纽埃", &[]),
    ("OM", "Oman", "阿曼", &[]),
    ("PA", "Panama", "巴拿马", &[]),
    ("PE", "Peru", "秘鲁", &[]),
    (
        "PF",
        "French Polynesia",
        "法属波利尼西亚",
        &["Polynesia", "波利尼西亚"],
    ),
    ("PG", "Papua New Guinea", "巴布亚新几内亚", &[]),
    ("PK", "Pakistan", "巴基斯坦", &[]),
    ("PL", "Poland", "波兰", &[]),
    ("PM", "Saint Pierre and Miquelon", "圣皮埃尔和密克隆", &[]),
    (
        "PN",
        "Pitcairn",
        "皮特凯恩",
        &["Pitcairn Islands", "皮特凯恩群岛"],
    ),
    ("PR", "Puerto Rico", "波多黎各", &["Porto Rico"]),
    (
        "PS",
        "State of Palestine",
        "巴勒斯坦国",
        &["Palestine", "巴勒斯坦"],
    ),
    ("PT", "Portugal", "葡萄牙", &["亚速尔群岛", "Azores"]),
    ("PW", "Palau", "帕劳", &["The Republic of Palau"]),
    ("PY", "Paraguay", "巴拉圭", &[]),
    ("QA", "Qatar", "卡塔尔", &[]),
    ("RA", "remote area of us", "美国偏远地区", &[]),
    (
        "RE",
        "Réunion",
        "留尼汪",
        &["Reunion", "Reunion Island", "留尼汪岛"],
    ),
    ("RO", "Romania", "罗马尼亚", &[]),
    ("RS", "Serbia", "塞尔维亚", &[]),
    (
        "RU",
        "Russian Federation",
        "俄罗斯联邦",
        &["Russian", "俄罗斯"],
    ),
    ("RW", "Rwanda", "卢旺达", &[]),
    ("SA", "Saudi Arabia", "沙特阿拉伯", &[]),
    ("SB", "Solomon Islands", "所罗门群岛", &[]),
    ("SC", "Seychelles", "塞舌尔", &[]),
    ("SD", "Sudan", "苏丹", &[]),
    ("SH", "Saint Helena", "圣赫勒拿", &[]),
    ("SI", "Slovenia", "斯洛文尼亚", &[]),
    (
        "SJ",
        "Svalbard and Jan Mayen Islands",
        "斯瓦尔巴群岛和扬马延岛",
        &["The Svalbard archipelago", "斯瓦尔巴岛和扬马延岛"],
    ),
    ("SK", "Slovakia", "斯洛伐克", &[]),
    ("SL", "Sierra Leone", "塞拉利昂", &[]),
    ("SM", "San Marino", "圣马力诺", &[]),
    ("SN", "Senegal", "塞内加尔", &[]),
    ("SO", "Somalia", "索马里", &["Somali"]),
    ("SR", "Suriname", "苏里南", &[]),
    ("SS", "South Sudan", "南苏丹", &["南苏丹共和国"]),
    ("ST", "Sao Tome and Principe", "圣多美和普林西比", &[]),
    ("SV", "El Salvador", "萨尔瓦多", &["Salvador"]),
    (
        "SX",
        "Sint Maarten (Dutch part)",
        "圣马丁（荷属）",
        &["St.Maarten", "荷属圣马丁"],
    ),
    (
        "SY",
        "Syrian Arab Republic",
        "阿拉伯叙利亚共和国",
        &["Syria", "叙利亚"],
    ),
    ("SZ", "Eswatini", "斯威士兰", &["Swaziland"]),
    ("TA", "Tristan da Cunha", "特里斯坦达库尼亚群岛", &[]),
    (
        "TC",
        "Turks and Caicos Islands",
        "特克斯和凯科斯群岛",
        &["The Turks and Caicos Islands"],
    ),
    ("TD", "Chad", "乍得", &[]),
    (
        "TF",
        "French Southern Territories",
        "法属南方领地",
        &["fashunanbulingdi", "法属南部领地"],
    ),
    ("TG", "Togo", "多哥", &[]),
    ("TJ", "Tajikistan", "塔吉克斯坦", &[]),
    ("TK", "Tokelau", "托克劳", &[]),
    (
        "TL",
        "Timor-Leste",
        "东帝汶",
        &["Democratic Republic of Timor-Leste"],
    ),
    ("TM", "Turkmenistan", "土库曼斯坦", &[]),
    ("TN", "Tunisia", "突尼斯", &["Tunis"]),
    ("TO", "Tonga", "汤加", &[]),
    ("TR", "Türkiye", "土耳其", &["Turkey", "Turkiye"]),
    ("TT", "Trinidad and Tobago", "多巴哥", &["特立尼达和多巴哥"]),
    ("TV", "Tuvalu", "图瓦卢", &[]),
    ("TW", "Taiwan China", "中国台湾", &[]),
    (
        "TZ",
        "United Republic of Tanzania",
        "坦桑尼亚联合共和国",
        &["Tanzania", "坦桑尼亚"],
    ),
    ("UA", "Ukraine", "乌克兰", &[]),
    ("UG", "Uganda", "乌干达", &[]),
    (
        "UM",
        "United States Minor Outlying Islands",
        "美国本土外小岛屿",
        &[],
    ),
    ("UY", "Uruguay", "乌拉圭", &[]),
    ("UZ", "Uzbekistan", "乌兹别克斯坦", &[]),
    ("VA", "Holy See", "教廷", &["Vatican", "梵蒂冈"]),
    (
        "VC",
        "Saint Vincent and the Grenadines",
        "圣文森特和格林纳丁斯",
        &[],
    ),
    (
        "VE",
        "Venezuela (Bolivarian Republic of)",
        "委内瑞拉玻利瓦尔共和国",
        &["Venezuela", "委内瑞拉"],
    ),
    (
        "VG",
        "British Virgin Islands",
        "英属维尔京群岛",
        &["THE BRITISH VRIGIN ISLANDS", "英属维尔京"],
    ),
    (
        "VI",
        "United States Virgin Islands",
        "美属维尔京群岛",
        &["The United States Virgin Islands"],
    ),
    ("VU", "Vanuatu", "瓦努阿图", &[]),
    (
        "WF",
        "Wallis and Futuna Islands",
        "瓦利斯群岛和富图纳群岛",
        &["Wallis et Futuna", "瓦利斯和富图纳群岛"],
    ),
    (
        "WS",
        "Samoa",
        "萨摩亚",
        &["西萨摩亚", "The Independent State of Samoa"],
    ),
    ("YE", "Yemen", "也门", &[]),
    (
        "YT",
        "Mayotte",
        "马约特",
        &["Territorial Collectivity of Mayotte"],
    ),
    ("ZA", "South Africa", "南非", &[]),
    ("ZM", "Zambia", "赞比亚", &[]),
    ("ZW", "Zimbabwe", "津巴布韦", &[]),
];
